- hosts: nodes
  become: yes
  tasks:
  - name: esnure docker is installed
    apt:
      name: docker.io
      state: latest
      update_cache: yes

  - name: esnure docker is installed
    apt:
      name: docker-compose
      state: latest
      update_cache: yes

  - name: add user to docker group
    user:
     name: vagrant
     groups: docker